multi stage build for alpine image + updating

diff --git a/alpine/Dockerfile b/alpine/Dockerfile
--- a/alpine/Dockerfile
+++ b/alpine/Dockerfile
@@ -1,13 +1,10 @@
 # Fetch stage #################################################################
 FROM alpine:3.12 AS fetchstage
 
-ARG gdal_version='3.1.4-r0'
-ENV GDAL_VERSION=${gdal_version}
-
 # Setup fetch deps
 RUN set -ex && \
  apk update && \
- apk add --no-cache --virtual .fetch-deps tar openssl git
+ apk add --no-cache --virtual .fetch-deps git
 
 # Fetch source code
 RUN set -x && \
@@ -16,37 +13,54 @@ RUN set -x && \
   cd cesium-terrain-builder && \
   git checkout master-quantized-mesh
 
+# Cleanup
+RUN  set -x && \
+  apk del .fetch-deps
+
 # Build stage #################################################################
 FROM alpine:3.12 AS buildstage
-COPY --from fetchstage /ctbtemp /ctbtemp
+COPY --from=fetchstage /ctbtemp /ctbtemp
+
+ARG gdal_version='3.1.4-r0'
+ENV GDAL_VERSION=${gdal_version}
 
 # Setup build deps
 RUN set -ex && \
+  apk update && \
   apk add --no-cache --virtual .build-deps \
     make cmake libxml2-dev g++ gdal-dev
 
 # Build & install cesium terrain builder
 RUN set -x && \
   cd /ctbtemp/cesium-terrain-builder && \
-  mkdir build && cd build && cmake .. && make install . && ls -lah /usr/bin/
-
-# Setup runtime deps
-RUN set -ex && \
-  apk add --no-cache --virtual .rundeps \
-  bash gdal=$GDAL_VERSION gdal-tools=$GDAL_VERSION
+  mkdir build && cd build && cmake .. && make install .
 
 # Cleanup
 RUN  set -x && \
-  apk del .fetch-deps .build-deps .build-deps-edge && \
+  apk del .build-deps && \
   rm -rf /tmp/* && \
   rm -rf /ctbtemp
 
-# Add some basic aliases
-RUN  echo 'alias ..="cd .."' >> ~/.bashrc && \
-  echo 'alias l="ls -CF --group-directories-first --color=auto"' >> ~/.bashrc && \
-  echo 'alias ll="ls -lFh --group-directories-first --color=auto"' >> ~/.bashrc && \
-  echo 'alias lla="ls -laFh --group-directories-first  --color=auto"' >> ~/.bashrc
+# Runtime stage #########################################################################
+FROM alpine:3.12 AS runtimestage
+COPY --from=buildstage /usr/local/include/ctb /usr/local/include/ctb
+COPY --from=buildstage /usr/local/lib/libctb.so /usr/local/lib/libctb.so
+COPY --from=buildstage /usr/local/bin/ctb-* /usr/local/bin/
+
+ARG gdal_version='3.1.4-r0'
+ENV GDAL_VERSION=${gdal_version}
 
 WORKDIR /data
+
+# Setup runtime deps
+RUN set -ex && \
+  apk update && \
+  apk add --no-cache --virtual .rundeps \
+  bash gdal=$GDAL_VERSION gdal-tools=$GDAL_VERSION && \
+  echo 'alias ..="cd .."' >> ~/.bashrc && \
+  echo 'alias l="ls -CF --group-directories-first --color=auto"' >> ~/.bashrc && \
+  echo 'alias ll="ls -lFh --group-directories-first --color=auto"' >> ~/.bashrc && \
+  echo 'alias lla="ls -laFh --group-directories-first  --color=auto"' >> ~/.bashrc && \
+  rm -rf /tmp/*
 
 CMD ["bash"]
